
services:
  redis:
    image: redis:7-alpine

  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=vexsx
      - POSTGRES_PASSWORD=New2021!
      - POSTGRES_DB=Bank_db
    volumes:
      - data-volume:/var/lib/postgresql/data

  api:
    image: vexsx/t6-porject:v1
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      - redis
      - postgres
    command: ["/app/main"]

volumes:
  data-volume:
