version: "3.9"
services:
  redis:
    image: redis:7-alpine

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - REDIS_ADDRESS=redis:6379
    depends_on:
      - redis
    entrypoint:
      - "/app/wait-for.sh"
      - "--"
      - "/app/start.sh"
    command: ["/app/main"]

volumes:
  data-volume: